services:
    php:
        build: docker/php
        container_name: zoo_php
        expose:
            - 9000
        restart: always
        volumes:
            - ./docker/php/conf/php.ini:/usr/local/etc/php/conf.d/custom.ini
            - ./docker/php/conf/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
            - ./backend:${PROJECT_ROOT}
        depends_on:
            - db
        networks:
            - symfony-network

    nginx:
        image: nginx:latest
        container_name: zoo_nginx
        ports:
            - ${VIRTUAL_PORT_BACKEND}:80
        restart: always
        volumes:
            - ./docker/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
            - ./backend:${PROJECT_ROOT}
        depends_on:
            - php
        networks:
            - symfony-network

    db:
        image: mariadb
        container_name: zoo_db
        restart: always
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        volumes:
            - ./backend/db:/var/lib/mysql
        ports:
            - 3306:3306
        networks:
            - symfony-network

    ui:
        build:
            context: .
            dockerfile: ./docker/ui/Dockerfile
        container_name: zoo_ui
        restart: always
        ports:
            - ${VIRTUAL_PORT_FRONTEND}:8080
        environment:
            NODE_ENV: production
        networks:
            - symfony-network

networks:
    symfony-network:
        driver: bridge
